### ISSUE TITLE
info.py is pulling test data.

### ISSUE THREAD

**Issue by wuftymerguftyguff** [kasbert/epsolar-tracer#11]
Hi,

How do I adapt info.py to query live data rather than pull the test data from testdata.py?

Also I assume that this should work with any usb->rs458 adapter with linux support?  (mine is based on ch341)

**Comment by kasbert** [comment]
see readall.py

#from pymodbus.client.sync import ModbusSerialClient as ModbusClient
from test.testdata import ModbusMockClient as ModbusClient

Any rs-485 adapter should work. Some devices may need an extra ioctl (https://www.kernel.org/doc/Documentation/serial/serial-rs485.txt).
Device name may be different, check line in readall.py:

client = ModbusClient(method='rtu', port='/dev/ttyXRUSB0', baudrate=115200, stopbits = 1, bytesize = 8, timeout=1)
