### ISSUE TITLE
Oddities with the device

### ISSUE THREAD

**Issue by delovoy** [kasbert/epsolar-tracer#21]
sudo insmod ./xr_usb_serial_common.ko

cat /etc/modprobe.d/bl.cdc_acm.conf 
blacklist cdc_acm 

tail -f / var / log / syslog -n 0  [1.txt](https://github.com/kasbert/epsolar-tracer/files/1313936/1.txt)

help

**Comment by delovoy** [comment]
cat /etc/issue.net 
Ubuntu 16.04.3 LTS

uname -a 
Linux IdeaPad 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I'm confused by errors, I did not check the module's functionality. Just do not want to screw up when programming the instruments. Are there any such mistakes?

**Comment by kasbert** [comment]
It may still work. I wouldn't worry about the errors.
Modem manager tries to use it as a modem and does not have a configuration for it.
mtp-probe checks if it is a camera or phone or something.

**Comment by delovoy** [comment]
thx
