### ISSUE TITLE
Is anyone getting full rated output from these charge controllers?

### ISSUE THREAD

**Issue by wrybread** [kasbert/epsolar-tracer#24]
I apologize if this is the wrong place to post this, but I don't know where else I might find other users of these charge controllers. Let me know if this is too off-topic, or if anyone knows of a better place to post.

I have 900 watts of panels (three 300 watt @ 36 volt panels) going into a Tracer 4210A 40 amp charge controller. That's connected to 4 Trojan T-105 batteries wired for 12 volts (450 amp hours). I recently set up a logging system using the excellent code here and I'm never getting more than 32 amps @ 14.5 volts to the battery (about 460 watts).  As the sun is going up my output will rise until it levels off at 32 amps. 

That's pretty close to 40 amps at 12 volts though (480 watts), so I'm wondering if the specs are a bit misleading? Shouldn't I be seeing 40 amps even when it's outputting 14.5 volts (580 watts)? Or is it in fact limiting the watts to 480 and calculating how many amps that would be at 12v?

It's not the biggest deal and I'm still really happy with this charge controller even after a year of heavy use, but I'm just wondering if anyone else is having this experience. And I also wonder whether for example the Morning Star MPPT 45 outputs a true 45 amps (even at 14.5 volts) or is also limited in this way.

(And on a sidenote, according to page 10 of [the manual]([url]http://www.epsolarpv.com/en/uploads/news/201710/1508812885787574.pdf(url)) we can connect up to 1550 watts of panels to this controller).

http://www.epsolarpv.com/en/uploads/news/201710/1508812885787574.pdf

**Comment by kasbert** [comment]
Yep, this isn't the best place to ask. Try googling for solar panel forums (for example https://www.solarpaneltalk.com/forum/off-grid-solar/off-grid-solar-panel-systems)

I don't know if epsolar charge controllers limit the current to less than rated. I have a 20A model, but I don't have enough panels to get constant maximum current. I have seen something like 16-18A.
