### ISSUE TITLE
cc1: error: code model kernel does not support PIC mode

### ISSUE THREAD

**Issue by delovoy** [kasbert/epsolar-tracer#29]
[PIC.txt](https://github.com/kasbert/epsolar-tracer/files/2019106/PIC.txt)

USER@Home:~$ uname -a 
Linux Home 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

USER@Home:~$ gcc --version
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0

USER@Home:~$ cat /etc/issue.net 
Ubuntu 18.04 LTS

Please adapt the code in PIC mode if this does not contradict your beliefs

**Comment by kasbert** [comment]
Closed as stale
