### ISSUE TITLE
Modbus specifications

### ISSUE THREAD

**Issue by CiSC87** [kasbert/epsolar-tracer#3]
Hello! First of all thanks a lot for sharing this code, very helpful.
Just a question. the modbus specifications attached seems to be related to another product from EPSolar: how did you know that they works with Tracer BN series as well? I have asked EPSolar for official docs but no luck for now...

**Comment by kasbert** [comment]
Hello,

I snooped the protocol between the windows application and the driver 
and it seemed to match the specification.
- Jarkko

**Comment by CiSC87** [comment]
Awesome! Both series of charge controllers seems to use the same remote monitoring equipment indeed (MT50). Just wanted to be sure :) Thanks again!
