### ISSUE TITLE
I have buy a Tracer and fw is from trion?

### ISSUE THREAD

**Issue by heiko1988** [kasbert/epsolar-tracer#33]
Good day,

I have question.

I have buy this Product, 
https://www.amazon.de/Solarladeregler-Tracer3210A-Solarpanel-Stromerzeuger-LCD-Display/dp/B07C22K5HD/ref=sr_1_cc_1?s=aps&ie=UTF8&qid=1537006034&sr=1-1-catcorr&keywords=tracer+3210

is a tracer 3210 and when i read the software details from the org. software from epever then i become this infos:
Device Model: TriRon3210
Device Version: V01.47+V03.11
Device SN: 00022013012xxxxx

Can i use ure Software to Read this Model?

**Comment by kasbert** [comment]
It should work. See also #9 .
Basically, if it works with MT50 display, it should work with this software.

**Comment by heiko1988** [comment]
Ok. Thanks.

I become. This script not run by me, I have a other found here of github,
and this work for me.

Thanks for you replay :)

Jarkko Sonninen <notifications@github.com> schrieb am Sa., 15. Sep. 2018,
17:22:
