### ISSUE TITLE
port to python 3

### ISSUE THREAD

**Issue by robinpaulson** [kasbert/epsolar-tracer#37]
Now that python 2 is unsupported, it'd be great to see this usable in version 3.

Will you accept pull requests if I do some of the work?

**Comment by kasbert** [comment]
sure

**Comment by robinpaulson** [comment]
I was about to put forward some PRs, when I saw this:
https://github.com/Salamek/epsolar-tracer
which is a fork of your repo. It's already py3 compatible, is ahead in a few other areas and is available for install with pip. I think I'll go with that for now, there's not been much activity on your repo for a while: 2.5 years maybe?

**Comment by kasbert** [comment]
That's nice. My controller is 500km away, so I don't use it so often.
