### ISSUE TITLE
USB-driver fails to compile with recent kernel-versions (5.4.119)

### ISSUE THREAD

**Issue by SvenRoederer** [kasbert/epsolar-tracer#39]
OpenWrt-21.02 uses Linux kernel 5.4.119 where the driver fails to compile, with 5.4.114 it was still working. 
According to https://github.com/openwrt/packages/pull/15666 there is a patch to make it build again. Not sure if it is still compatible with older kernels then.

[Log when compiling with linux5.4.119 / Openwrt-21.02.txt](https://github.com/kasbert/epsolar-tracer/files/6534663/compile_linux5.4.119_Openwrt-21.02.txt)

**Comment by kasbert** [comment]
I just applied the openwrt change. We'll see if there are older kernel users

**Comment by kasbert** [comment]
@SvenRoederer Please could you try the experimental kernel driver in directory linux_usb_serial ?
It implements the RS-485 ioctls. The device would be /dev/ttyUSB0 and the client code needs something like:
```
import serial.rs485

client.socket.rs485_mode = serial.rs485.RS485Settings()

```

**Comment by kasbert** [comment]
I guess this was resolved. Closing.
