### ISSUE TITLE
ERROR: could not insert module ./xr_usb_serial_common.ko: Invalid module format

### ISSUE THREAD

**Issue by kevinkey619** [kasbert/epsolar-tracer#40]
I keep getting the below error:

sudo insmod ./xr_usb_serial_common.ko
insmod: ERROR: could not insert module ./xr_usb_serial_common.ko: Invalid module format

**Comment by kasbert** [comment]
does "dmesg" command reveal anything ?

**Comment by kevinkey619** [comment]
Thanks for the quick reply. I'm fairly technically savvy, but I'm more of a DOS/Windows person. Not a Linux expert. Here you go:

pi@raspberrypi:~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.10.63-v7+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1450 SMP Wed Sep 8 14:29:23 BST 2021
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Rev 1.2
[    0.000000] random: fast init done
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Reserved memory: created CMA memory pool at 0x37400000, size 64 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x000000003b3fffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000003b3fffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000003b3fffff]
[    0.000000] On node 0 totalpages: 242688
[    0.000000]   DMA zone: 2133 pages used for memmap
[    0.000000]   DMA zone: 0 pages reserved
[    0.000000]   DMA zone: 242688 pages, LIFO batch:63
[    0.000000] percpu: Embedded 20 pages/cpu s50828 r8192 d22900 u81920
[    0.000000] pcpu-alloc: s50828 r8192 d22900 u81920 alloc=20*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=1280 bcm2708_fb.fbheight=720 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=tty1 console=ttyS0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
[    0.000000] Kernel parameter elevator= does not have any effect anymore.
               Please use sysfs to set IO scheduler for individual devices.
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 878804K/970752K available (10240K kernel code, 1312K rwdata, 2948K rodata, 1024K init, 863K bss, 26412K reserved, 65536K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 32055 entries in 63 pages
[    0.000000] ftrace: allocated 63 pages with 6 groups
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000]  Rude variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] random: get_random_bytes called from start_kernel+0x3ac/0x580 with crng_init=1
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000024] Switching to timer-based delay loop, resolution 52ns
[    0.000308] Console: colour dummy device 80x30
[    0.001176] printk: console [tty1] enabled
[    0.001247] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.001305] pid_max: default: 32768 minimum: 301
[    0.001523] LSM: Security Framework initializing
[    0.001776] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.001826] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.003275] cgroup: Disabling memory control group subsystem
[    0.003553] CPU: Testing write buffer coherency: ok
[    0.004049] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.005292] Setting up static identity map for 0x100000 - 0x10003c
[    0.005499] rcu: Hierarchical SRCU implementation.
[    0.006424] smp: Bringing up secondary CPUs ...
[    0.007576] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.008828] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.010121] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.010279] smp: Brought up 1 node, 4 CPUs
[    0.010332] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.010363] CPU: All CPU(s) started in HYP mode.
[    0.010390] CPU: Virtualization extensions available.
[    0.011371] devtmpfs: initialized
[    0.029015] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.029327] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.029387] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.032604] pinctrl core: initialized pinctrl subsystem
[    0.033779] NET: Registered protocol family 16
[    0.037938] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.043625] audit: initializing netlink subsys (disabled)
[    0.044504] thermal_sys: Registered thermal governor 'step_wise'
[    0.045440] audit: type=2000 audit(0.040:1): state=initialized audit_enabled=0 res=1
[    0.045668] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.045709] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.046017] Serial: AMBA PL011 UART driver
[    0.065729] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.080144] raspberrypi-firmware soc:firmware: Attached to firmware from 2021-08-31T14:55:00, variant start
[    0.090155] raspberrypi-firmware soc:firmware: Firmware hash is 67615e950e1e28b92dfae6303cf7a8b879a8908f
[    0.134293] Kprobes globally optimized
[    0.139353] bcm2835-dma 3f007000.dma: DMA legacy API manager, dmachans=0x1
[    0.141768] SCSI subsystem initialized
[    0.142046] usbcore: registered new interface driver usbfs
[    0.142131] usbcore: registered new interface driver hub
[    0.142223] usbcore: registered new device driver usb
[    0.144313] clocksource: Switched to clocksource arch_sys_counter
[    1.917529] VFS: Disk quotas dquot_6.6.0
[    1.917670] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    1.917894] FS-Cache: Loaded
[    1.918139] CacheFiles: Loaded
[    1.928134] NET: Registered protocol family 2
[    1.928403] IP idents hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    1.930112] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    1.930200] TCP established hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    1.930346] TCP bind hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    1.930560] TCP: Hash tables configured (established 8192 bind 8192)
[    1.930746] UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
[    1.930824] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[    1.931502] NET: Registered protocol family 1
[    1.932314] RPC: Registered named UNIX socket transport module.
[    1.932351] RPC: Registered udp transport module.
[    1.932380] RPC: Registered tcp transport module.
[    1.932409] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    1.934175] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    1.938066] Initialise system trusted keyrings
[    1.938354] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    1.947925] zbud: loaded
[    1.950003] FS-Cache: Netfs 'nfs' registered for caching
[    1.950911] NFS: Registering the id_resolver key type
[    1.950972] Key type id_resolver registered
[    1.951001] Key type id_legacy registered
[    1.951171] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    1.951206] nfs4flexfilelayout_init: NFSv4 Flexfile Layout Driver Registering...
[    1.952405] Key type asymmetric registered
[    1.952438] Asymmetric key parser 'x509' registered
[    1.952509] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    1.952549] io scheduler mq-deadline registered
[    1.952579] io scheduler kyber registered
[    1.957428] bcm2708_fb soc:fb: FB found 1 display(s)
[    1.989457] Console: switching to colour frame buffer device 160x45
[    2.005380] bcm2708_fb soc:fb: Registered framebuffer for display 0, size 1280x720
[    2.009356] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    2.010282] bcm2835-aux-uart 3f215040.serial: there is not valid maps for state default
[    2.012256] bcm2835-rng 3f104000.rng: hwrng registered
[    2.012870] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    2.013896] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    2.026354] brd: module loaded
[    2.038603] loop: module loaded
[    2.040583] Loading iSCSI transport class v2.0-870.
[    2.042332] libphy: Fixed MDIO Bus: probed
[    2.042745] usbcore: registered new interface driver lan78xx
[    2.042973] usbcore: registered new interface driver smsc95xx
[    2.043159] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    2.771519] Core Release: 2.80a
[    2.771636] Setting default values for core params
[    2.777349] Finished setting default values for core params
[    2.983321] Using Buffer DMA mode
[    2.988861] Periodic Transfer Interrupt Enhancement - disabled
[    2.994442] Multiprocessor Interrupt Enhancement - disabled
[    2.999985] OTG VER PARAM: 0, OTG VER FLAG: 0
[    3.005508] Dedicated Tx FIFOs mode

[    3.011564] WARN::dwc_otg_hcd_init:1074: FIQ DMA bounce buffers: virt = b7504000 dma = 0xf7504000 len=9024
[    3.022759] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    3.050812] dwc_otg: Microframe scheduler enabled

[    3.050885] WARN::hcd_init_fiq:457: FIQ on core 1

[    3.061783] WARN::hcd_init_fiq:458: FIQ ASM at 807c9978 length 36

[    3.072688] WARN::hcd_init_fiq:497: MPHI regs_base at bb810000
[    3.083776] dwc_otg 3f980000.usb: DWC OTG Controller
[    3.089359] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    3.094956] dwc_otg 3f980000.usb: irq 89, io mem 0x00000000
[    3.100509] Init: Port Power? op_state=1
[    3.106008] Init: Power Port (0)
[    3.111767] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.10
[    3.117319] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    3.122837] usb usb1: Product: DWC OTG Controller
[    3.128394] usb usb1: Manufacturer: Linux 5.10.63-v7+ dwc_otg_hcd
[    3.133976] usb usb1: SerialNumber: 3f980000.usb
[    3.140240] hub 1-0:1.0: USB hub found
[    3.145807] hub 1-0:1.0: 1 port detected
[    3.152379] dwc_otg: FIQ enabled
[    3.152392] dwc_otg: NAK holdoff enabled
[    3.152404] dwc_otg: FIQ split-transaction FSM enabled
[    3.152422] Module dwc_common_port init
[    3.152768] usbcore: registered new interface driver usb-storage
[    3.158339] mousedev: PS/2 mouse device common for all mice
[    3.165057] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    3.172868] sdhci: Secure Digital Host Controller Interface driver
[    3.178154] sdhci: Copyright(c) Pierre Ossman
[    3.183935] mmc-bcm2835 3f300000.mmcnr: could not get clk, deferring probe
[    3.189942] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    3.195554] sdhci-pltfm: SDHCI platform and OF driver helper
[    3.202682] ledtrig-cpu: registered to indicate activity on CPUs
[    3.208478] hid: raw HID events driver (C) Jiri Kosina
[    3.214132] usbcore: registered new interface driver usbhid
[    3.219606] usbhid: USB HID core driver
[    3.230111] Initializing XFRM netlink socket
[    3.235632] NET: Registered protocol family 17
[    3.241149] Key type dns_resolver registered
[    3.247200] Registering SWP/SWPB emulation handler
[    3.252669] registered taskstats version 1
[    3.257983] Loading compiled-in X.509 certificates
[    3.264111] Key type ._fscrypt registered
[    3.269416] Key type .fscrypt registered
[    3.274863] Indeed it is in host mode hprt0 = 00021501
[    3.284373] Key type fscrypt-provisioning registered
[    3.301272] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    3.306633] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 114, base_baud = 0) is a PL011 rev2
[    3.314720] bcm2835-aux-uart 3f215040.serial: there is not valid maps for state default
[    3.320855] printk: console [ttyS0] disabled
[    3.326480] 3f215040.serial: ttyS0 at MMIO 0x3f215040 (irq = 86, base_baud = 50000000) is a 16550
[    3.484354] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    3.488912] printk: console [ttyS0] enabled
[    3.502621] Indeed it is in host mode hprt0 = 00001101
[    3.511352] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    3.764671] usb 1-1: New USB device found, idVendor=0424, idProduct=9514, bcdDevice= 2.00
[    3.771395] mmc-bcm2835 3f300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    3.774130] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.781200] mmc-bcm2835 3f300000.mmcnr: DMA channel allocated
[    3.828301] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    3.848416] hub 1-1:1.0: USB hub found
[    3.854876] sdhost: log_buf @ (ptrval) (f7507000)
[    3.858741] hub 1-1:1.0: 5 ports detected
[    3.885680] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    4.204341] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    4.210172] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    4.344668] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00, bcdDevice= 2.00
[    4.348123] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    4.363187] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    4.365965] smsc95xx v2.0.0
[    4.399489] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    4.460311] libphy: smsc95xx-mdiobus: probed
[    4.486255] of_cfs_init
[    4.488675] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:6f:e8:24
[    4.499614] of_cfs_init: OK
[    4.583607] mmc0: host does not support reading read-only switch, assuming write-enable
[    4.664342] usb 1-1.2: new high-speed USB device number 4 using dwc_otg
[    4.674040] mmc0: new high speed SDHC card at address aaaa
[    4.826157] usb 1-1.2: New USB device found, idVendor=0bda, idProduct=2838, bcdDevice= 1.00
[    4.841470] mmcblk0: mmc0:aaaa SK32G 29.7 GiB
[    4.859448] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.859467] usb 1-1.2: Product: RTL2838UHIDIR
[    4.910011]  mmcblk0: p1 p2
[    4.922751] usb 1-1.2: Manufacturer: Realtek
[    4.922769] usb 1-1.2: SerialNumber: 00000001
[    4.989402] mmc1: new high speed SDIO card at address 0001
[    5.144355] usb 1-1.3: new full-speed USB device number 5 using dwc_otg
[    5.347773] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    5.368172] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    5.386999] devtmpfs: mounted
[    5.405684] Freeing unused kernel memory: 1024K
[    5.434834] Run /sbin/init as init process
[    5.448253]   with arguments:
[    5.448265]     /sbin/init
[    5.448276]   with environment:
[    5.448288]     HOME=/
[    5.448299]     TERM=linux
[    5.480521] usb 1-1.3: New USB device found, idVendor=046d, idProduct=c534, bcdDevice=29.01
[    5.501117] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    5.519866] usb 1-1.3: Product: USB Receiver
[    5.533528] usb 1-1.3: Manufacturer: Logitech
[    5.555684] input: Logitech USB Receiver as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:046D:C534.0001/input/input0
[    5.645467] hid-generic 0003:046D:C534.0001: input,hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-3f980000.usb-1.3/input0
[    5.682299] input: Logitech USB Receiver Mouse as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C534.0002/input/input1
[    5.711166] input: Logitech USB Receiver Consumer Control as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C534.0002/input/input2
[    5.804834] input: Logitech USB Receiver System Control as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C534.0002/input/input3
[    5.835085] hid-generic 0003:046D:C534.0002: input,hiddev96,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-3f980000.usb-1.3/input1
[    5.964472] usb 1-1.5: new full-speed USB device number 6 using dwc_otg
[    6.101037] systemd[1]: System time before build time, advancing clock.
[    6.122776] usb 1-1.5: New USB device found, idVendor=04e2, idProduct=1411, bcdDevice= 0.01
[    6.144126] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    6.163733] usb 1-1.5: Product: XR21B1411
[    6.177922] usb 1-1.5: Manufacturer: Exar Corp.
[    6.192915] usb 1-1.5: SerialNumber: G4441989341
[    6.268695] NET: Registered protocol family 10
[    6.285133] Segment Routing with IPv6
[    6.401341] systemd[1]: systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    6.452950] systemd[1]: Detected architecture arm.
[    6.585393] systemd[1]: Set hostname to <raspberrypi>.
[    7.706949] random: systemd: uninitialized urandom read (16 bytes read)
[    7.745209] random: systemd: uninitialized urandom read (16 bytes read)
[    7.767823] systemd[1]: Created slice system-serial\x2dgetty.slice.
[    7.824693] random: systemd: uninitialized urandom read (16 bytes read)
[    7.842988] systemd[1]: Reached target Swap.
[    7.884921] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    7.945233] systemd[1]: Listening on udev Kernel Socket.
[    7.995367] systemd[1]: Listening on Syslog Socket.
[    8.045658] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    8.105399] systemd[1]: Listening on udev Control Socket.
[    8.469252] i2c /dev entries driver
[    9.772207] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   10.086167] systemd-journald[130]: Received request to flush runtime journal from PID 1
[   10.921111] mc: Linux media interface: v0.10
[   10.926904] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[   10.930573] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[   10.930612] [vc_sm_connected_init]: start
[   10.961088] [vc_sm_connected_init]: installed successfully
[   10.991403] videodev: Linux video capture interface: v2.00
[   11.039196] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[   11.045181] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   11.048722] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   11.059748] bcm2835_audio bcm2835_audio: card created with 4 channels
[   11.066014] bcm2835_audio bcm2835_audio: card created with 4 channels
[   11.078179] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[   11.108422] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[   11.108484] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[   11.119090] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[   11.119146] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[   11.123138] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[   11.123194] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[   11.157978] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[   11.165668] bcm2835_isp: module is from the staging directory, the quality is unknown, you have been warned.
[   11.211261] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video13
[   11.215696] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video14
[   11.216303] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video15
[   11.216680] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video16
[   11.216716] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[   11.216757] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[   11.216779] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[   11.216800] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[   11.217016] bcm2835-isp bcm2835-isp: Loaded V4L2 bcm2835-isp
[   11.476360] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   11.594047] xr_usb_serial_common: disagrees about version of symbol module_layout
[   11.594226] xr_usb_serial_common: disagrees about version of symbol module_layout
[   11.633294] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   11.718092] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[   11.728946] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   11.729834] usbcore: registered new interface driver brcmfmac
[   11.883484] logitech-djreceiver 0003:046D:C534.0001: hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-3f980000.usb-1.3/input0
[   11.979185] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   11.979371] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   11.979459] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[   11.980421] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Oct 22 2019 01:59:28 version 7.45.98.94 (r723000 CY) FWID 01-3b33decd
[   12.022936] random: crng init done
[   12.022960] random: 7 urandom warning(s) missed due to ratelimiting
[   12.350380] logitech-djreceiver 0003:046D:C534.0002: hiddev96,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-3f980000.usb-1.3/input1
[   12.418519] logitech-djreceiver 0003:046D:C534.0002: device of type eQUAD nano Lite (0x0a) connected on slot 1
[   12.420516] logitech-djreceiver 0003:046D:C534.0002: device of type eQUAD nano Lite (0x0a) connected on slot 2
[   12.422999] input: Logitech Wireless Keyboard PID:4023 Keyboard as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C534.0002/0003:046D:4023.0003/input/input6
[   12.429400] input: Logitech Wireless Keyboard PID:4023 Consumer Control as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C534.0002/0003:046D:4023.0003/input/input7
[   12.430111] input: Logitech Wireless Keyboard PID:4023 System Control as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C534.0002/0003:046D:4023.0003/input/input8
[   12.435811] hid-generic 0003:046D:4023.0003: input,hidraw2: USB HID v1.11 Keyboard [Logitech Wireless Keyboard PID:4023] on usb-3f980000.usb-1.3/input1:1
[   12.438646] input: Logitech Wireless Mouse PID:4054 Mouse as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C534.0002/0003:046D:4054.0004/input/input13
[   12.439453] hid-generic 0003:046D:4054.0004: input,hidraw3: USB HID v1.11 Mouse [Logitech Wireless Mouse PID:4054] on usb-3f980000.usb-1.3/input1:2
[   13.274548] Under-voltage detected! (0x00050005)
[   13.405600] input: Logitech Wireless Keyboard PID:4023 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C534.0002/0003:046D:4023.0003/input/input17
[   13.407538] logitech-hidpp-device 0003:046D:4023.0003: input,hidraw2: USB HID v1.11 Keyboard [Logitech Wireless Keyboard PID:4023] on usb-3f980000.usb-1.3/input1:1
[   13.522884] input: Logitech Wireless Mouse as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C534.0002/0003:046D:4054.0004/input/input18
[   13.523883] logitech-hidpp-device 0003:046D:4054.0004: input,hidraw3: USB HID v1.11 Mouse [Logitech Wireless Mouse] on usb-3f980000.usb-1.3/input1:2
[   14.184920] uart-pl011 3f201000.serial: no DMA platform data
[   14.329068] 8021q: 802.1Q VLAN Support v1.8
[   15.074548] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[   15.149925] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[   15.827169] SMSC LAN8700 usb-001:003:01: attached PHY driver [SMSC LAN8700] (mii_bus:phy_addr=usb-001:003:01, irq=POLL)
[   15.827627] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   15.843815] smsc95xx 1-1.1:1.0 eth0: Link is Down
[   16.710209] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   19.272158] Bluetooth: Core ver 2.22
[   19.272307] NET: Registered protocol family 31
[   19.272324] Bluetooth: HCI device and connection manager initialized
[   19.272369] Bluetooth: HCI socket layer initialized
[   19.272390] Bluetooth: L2CAP socket layer initialized
[   19.272426] Bluetooth: SCO socket layer initialized
[   19.289099] Bluetooth: HCI UART driver ver 2.3
[   19.289127] Bluetooth: HCI UART protocol H4 registered
[   19.289269] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   19.289600] Bluetooth: HCI UART protocol Broadcom registered
[   19.806656] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   19.806680] Bluetooth: BNEP filters: protocol multicast
[   19.806714] Bluetooth: BNEP socket layer initialized
[   19.899482] Bluetooth: RFCOMM TTY layer initialized
[   19.899537] Bluetooth: RFCOMM socket layer initialized
[   19.899574] Bluetooth: RFCOMM ver 1.11
pi@raspberrypi:~ $

**Comment by kasbert** [comment]
Try:
        To remove the CDC-ACM driver and install the driver:

        # rmmod cdc-acm
        # modprobe -r usbserial
        # modprobe usbserial
        # insmod ./xr_usb_serial_common.ko

        # file ./xr_usb_serial_common.ko 
        ./xr_usb_serial_common.ko: ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), 
        BuildID[sha1]=9da89b6ed09912808a7ae9de591584fd1c1bbb5f, not stripped

**Comment by kevinkey619** [comment]
Thanks, but no luck. I still end up with the same error message even after performing all 4 steps:

 sudo insmod ./xr_usb_serial_common.ko
insmod: ERROR: could not insert module ./xr_usb_serial_common.ko: Invalid module format

**Comment by kevinkey619** [comment]
My Raspberry Pi micro SD card died last night. This might have been the problem. Going to get a new card and reinstall everything. I'll let you know if the problem goes away.

**Comment by kevinkey619** [comment]
Yeah, the problem was with the failing micro SD card on my Raspberry Pi. New card, reinstall, and all is well now.
