### ISSUE TITLE
Warnings but no errors on latest

### ISSUE THREAD

**Issue by jimlynnjulian** [kasbert/epsolar-tracer#45]
RPi-3B/Raspbian Bullseye Full, updated and upgraded.

make
make -C /lib/modules/5.15.56-v7+/build M=/var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a
make[1]: Entering directory '/usr/src/linux-headers-5.15.56-v7+'
  CC [M]  /var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.o
/var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.c: In function ‘xr_usb_serial_ctrl_irq’:
/var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.c:261:21: warning: unused variable ‘tty’ [-Wunused-variable]
  261 |  struct tty_struct *tty;
      |                     ^~~
/var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.c: In function ‘xr_usb_serial_process_read_urb’:
/var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.c:393:21: warning: unused variable ‘tty’ [-Wunused-variable]
  393 |  struct tty_struct *tty;
      |                     ^~~
/var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.c: In function ‘xr_usb_serial_softint’:
/var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.c:468:21: warning: unused variable ‘tty’ [-Wunused-variable]
  468 |  struct tty_struct *tty;
      |                     ^~~
/var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.c: In function ‘xr_usb_serial_reset_resume’:
/var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.c:1634:21: warning: unused variable ‘tty’ [-Wunused-variable]
 1634 |  struct tty_struct *tty;
      |                     ^~~
  MODPOST /var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/Module.symvers
  CC [M]  /var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.mod.o
  LD [M]  /var/www/html/epsolar-tracer-kaspbert/xr_usb_serial_common-1a/xr_usb_serial_common.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.15.56-v7+'

**Comment by kasbert** [comment]
Fixed
