### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jimlynnjulian** [kasbert/epsolar-tracer#46]
I'm finding several broken links on the GWL site. No Windows software download is among them.
The Exar driver 'Original source' link is broken as well.

**Comment by CdriFry** [comment]
Hi, What software would you need exactly? I may have what you need

**Comment by kasbert** [comment]
Have you tried these: https://www.epever.com/support/softwares/ ?

**Comment by jimlynnjulian** [comment]
Finding the software was not a problem. Just reporting some broken links from the Readme.md.

**Comment by kasbert** [comment]
Thanks for the info. I updated the texts.
