### ISSUE TITLE
difficulty to compile xr_usb_serial_common

### ISSUE THREAD

**Issue by sante85** [kasbert/epsolar-tracer#51]
I have tryed to compile on centos 7 with kernel 3.10.

tty_port_initialized not found

It possible deploy a .ko ?

thanks

**Comment by kasbert** [comment]
Oh well. I'm not going to put effort in porting to ten year old kernel. Sorry.

**Comment by sante85** [comment]
which distro you suggest to proceed with right compile?

Il giorno lun 20 mar 2023 alle ore 18:43 Jarkko Sonninen <
***@***.***> ha scritto:
