### ISSUE TITLE
Wiring information

### ISSUE THREAD

**Issue by pterodyne** [kasbert/epsolar-tracer#55]
Thanks for adding the wiring information.  I am wiring up my USB to FTDI RS485.  The wiring info all makes sense except one thing Im not sure about.  My adapter has 3.3 and 5v outputs. Any thoughts on which one I should use? or neither?  Both ends have power, so it seems like just ground would need to be hooked up (and A+ B- of course).

Thanks!'

Bryan

**Comment by kasbert** [comment]
Don't use either voltage. The wire provides voltage to the MT-50 display.
