### ISSUE TITLE
help with code

### ISSUE THREAD

**Issue by lzahradil** [kasbert/epsolar-tracer#6]
Hi Kasbert,

Excuse my English. Google Translator :)

I would like to ask how do I put the PV input voltage, PV current, battery voltage, etc ... to variables that I could then use the HTTP GET sending to the server.

Unfortunately python nothing to me. I managed to create a script that will give me the following values but can not be used as a variable. I do not know how :(

{0 'EPsolar Tech CO., Ltd.', 1 'Tracer4215BN', 2 'V02.14 V07.24 +'}
PV voltage (uPV): 15000 V
Current PV (iPV): 4000
PV voltage (uPV): 15000 V
Current PV (iPV): 4000
PV voltage (uPV): 15000 V
Current PV (iPV): 4000

I assume that the value has yet to be somehow processed. E.g. value / 100?
I need to get the following:

HTTP GET: http://server_address/script.php?timestamp=timestamp&uPV=value PV voltage&iPV=value PV current&...

Could you kick me in the right direction or a better example of a piece of code as I could finish.

Thank you very much.

**Comment by kasbert** [comment]
Closing as stale
