### ISSUE TITLE
B-series MODBUS specification reference manual available

### ISSUE THREAD

**Issue by merald** [kasbert/epsolar-tracer#7]
Hi,

I have the reference manual for the epsolar protocol, and would gladly share. Please let me know if you need it. Thanks

**Comment by kasbert** [comment]
Yes, I am interested.
Would you send it to epsolar-tracer@dungeon.fi or a link to somewhere, please.

**Comment by kasbert** [comment]
Thanks.

**Comment by henkenli** [comment]
Hi, I am also interested.
Would you like to mail it or a link to henriksepost@me.com please.

**Comment by kasbert** [comment]
It's in the archive directory.

**Comment by henkenli** [comment]
Thanks!
